import utils.constants
from utils import utils, constants, properties as props
from Storage import mongo_client
import logging
from bs4 import BeautifulSoup

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)


class HPCL:
    def __init__(self):
        self.count = 0
        pass

    curl_template_map = {
        constants.HPCL_CURL: """curl 'http://hproroute.hpcl.co.in/ROAlongRoute/RoInRadius_data_dt_plus.jsp?product_type=MS&facility=any&selected_facilities_names=MS_HSD&D=__city_code__&Q=2' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36' -H 'Accept: */*' -H 'Referer: http://hproroute.hpcl.co.in/ROAlongRoute/index.jsp' -H 'Connection: keep-alive' --compressed"""
    }

    @staticmethod
    def get_retailer():
        return constants.hpcl

    @staticmethod
    def store_dto(dto):
        mongo_client.insert_dto(props.COLL_HPCL, dto)

    District_Codes = {
        constants.ANDHRA_PRADESH: {
            "002": "ANANTAPUR",
            "003": "CHITTOOR",
            "004": "CUDDAPAH",
            "005": "EAST GODAVARI",
            "006": "GUNTUR",
            "011": "KRISHNA",
            "012": "KURNOOL",
            "017": "NELLORE",
            "007": "PRAKASAM",
            "019": "SRIKAKULAM",
            "020": "VISAKHAPATNAM",
            "021": "VIZIANAGARAM",
            "023": "WEST GODAVARI"
        },
        constants.Andaman_and_Nicobar_Islands: {
            "580": "ANDAMAN"
        },
        constants.Arunachal_Pradesh: {
            "642": "ANJAW",
            "592": "CHANGLANG",
            "590": "DEBANG VALLEY",
            "582": "KAMENG(EAST)",
            "581": "KAMENG(WEST)",
            "640": "KURUNG KUMEY",
            "583": "LOHIT",
            "641": "LOWER DEBANG VALLEY",
            "587": "LOWER SUBANSIRI",
            "584": "PAPUM PARE",
            "586": "SIANG(EAST)",
            "585": "SIANG(WEST)",
            "591": "TAWANG",
            "589": "TIRAP",
            "643": "UPPER SIANG",
            "588": "UPPER SUBANSIRI"
        },
        constants.Assam: {
            "039": "BARPETA",
            "630": "BASKA",
            "044": "BONGAIGAON",
            "024": "CACHAR",
            "629": "CHIRANG",
            "038": "DARRANG",
            "045": "DHEMAJI",
            "041": "DHUBRI",
            "032": "DIBRUGARH",
            "028": "GOALPARA NORTH",
            "027": "GOALPARA SOUTH",
            "026": "GOLAGHAT",
            "046": "HAILAKANDI",
            "042": "JORHAT",
            "029": "KAMRUP",
            "036": "KARBI ANGLONG",
            "043": "KARIMGANJ",
            "040": "KOKRAJHAR",
            "031": "LAKHIMPUR",
            "047": "MARIGAON",
            "037": "N-CACHAR  HILLS",
            "033": "NAGAON",
            "030": "NALBARI",
            "034": "PRAGJYOTISHPUR",
            "035": "SIBSAGAR",
            "025": "SONITPUR",
            "617": "TAN",
            "048": "TINSUKIA",
            "631": "UDALGURI"
        },
        constants.Bihar: {
            "071": "ARARIA",
            "627": "ARWAL",
            "049": "AURANGABAD",
            "055": "BANKA",
            "051": "BEGUSARAI",
            "082": "BHABHUA",
            "050": "BHAGALPUR",
            "079": "BHOJPUR(ARRAH)",
            "085": "BUXAR",
            "052": "CHAMPARAN-EAST",
            "053": "CHAMPARAN-WEST",
            "054": "DARBHANGA",
            "056": "GAYA",
            "057": "GOPALGANJ",
            "087": "JAMUI",
            "080": "JEHANABAD",
            "059": "KATIHAR",
            "061": "KHAGARIA",
            "073": "KISHENGANJ",
            "088": "LAKHISARAI",
            "084": "MADHEPURA",
            "062": "MADHUBANI",
            "058": "MONGHYR",
            "060": "MUZZAFARPUR",
            "064": "NALANDA",
            "066": "NAWADAH",
            "067": "PATNA",
            "063": "PATNA(LOCAL)",
            "065": "PURNEA",
            "083": "ROHTAS(SASARAM)",
            "068": "SAHARSA",
            "069": "SAMASTIPUR",
            "070": "SANTHAL PARGAN",
            "072": "SARAN",
            "086": "SHEIKHPURA",
            "626": "SHEOHAR",
            "074": "SITAMARHI",
            "076": "SIWAN",
            "077": "SUPAUL",
            "078": "VAISHALI"
        },
        constants.Chandigarh: {
            "593": "CHANDIGARH"
        },
        constants.Chhattisgarh: {
            "685": "BALOD",
            "680": "BALODABAZAR",
            "688": "BALRAMPUR",
            "500": "BASTAR",
            "687": "BEMETARA",
            "644": "BIJAPUR",
            "501": "BILASPUR",
            "502": "DANTEWARA",
            "503": "DHAMTARI",
            "504": "DURG",
            "681": "GARIYABAND",
            "505": "JANJGIR",
            "506": "JASHPUR",
            "507": "KANKER",
            "508": "KAWARDA",
            "682": "KONDAGAON",
            "509": "KORBA",
            "510": "KORIA",
            "511": "MAHASAMUND",
            "686": "MUNGELI",
            "645": "NARAINPUR",
            "512": "RAIGARH",
            "513": "RAIPUR",
            "514": "RAJANANDGAON",
            "515": "SARGUJA",
            "683": "SUKMA",
            "684": "SURAJPUR"
        },
        constants.Daman_and_Diu: {
            "596": "DAMAN",
            "597": "DIU"
        },
        constants.Delhi: {
            "672": "CENTRAL DELHI",
            "594": "DELHI",
            "671": "EAST DELHI",
            "673": "NEW DELHI",
            "669": "NORTH DELHI",
            "670": "NORTH EAST DELHI",
            "668": "NORTH WEST DELHI",
            "694": "SHAHDARA DELHI",
            "674": "SOUTH DELHI",
            "693": "SOUTH EAST DELHI",
            "675": "SOUTH WEST DELHI",
            "676": "WEST DELHI"
        },
        constants.Dadra_and_Nagar_Haveli: {
            "595": "DADRA-N-HAVELI"
        },
        constants.Goa: {
            "089": "NORTH GOA",
            "090": "SOUTH GOA"
        },
        constants.Gujarat: {
            "091": "AHMEDABAD",
            "092": "AMRELI",
            "112": "ANAND",
            "695": "ARVALLI",
            "093": "BANASKAHTHA",
            "096": "BHARUCH",
            "095": "BHAVNAGAR",
            "696": "BOTAD",
            "697": "CHHOTAUDEPUR",
            "114": "DAHOD",
            "698": "DEVBHUMI DWARKA",
            "098": "GANDHINAGAR",
            "699": "GIR SOMNATH",
            "099": "JAMNAGAR",
            "100": "JUNAGADH",
            "101": "KHEDA (KAIRA)",
            "102": "KUTCH",
            "700": "MAHISAGAR",
            "103": "MEHSANA",
            "701": "MORBI",
            "110": "NARMADA",
            "115": "NAVSARI",
            "104": "PANCH MAHALS",
            "113": "PATAN",
            "111": "PORBUNDER",
            "105": "RAJKOT",
            "106": "SABARKANTHA",
            "107": "SURAT",
            "108": "SURENDRANAGAR",
            "657": "TAPI",
            "097": "THE DANGS",
            "094": "VADODARA",
            "109": "VALSAD"
        },
        constants.Himachal_Pradesh: {
            "488": "BILASPUR",
            "489": "CHAMBA",
            "491": "HAMIRPUR",
            "490": "KANGRA",
            "492": "KINNAUR",
            "493": "KULU",
            "494": "LAHAUL SPITI",
            "495": "MANDI",
            "496": "SIMLA",
            "497": "SIRMOOR",
            "498": "SOLON",
            "499": "UNA"
        },
        constants.Haryana: {
            "471": "AMBALA",
            "472": "BHIWANI",
            "474": "FARIDABAD",
            "625": "FATEHABAD",
            "473": "GURGAON",
            "475": "HISSAR",
            "607": "JHAJJAR",
            "476": "JIND",
            "477": "KAITHAL",
            "478": "KARNAL",
            "479": "KURUKSHETRA",
            "480": "MAHENDERGARH",
            "611": "MEWAT",
            "667": "PALWAL",
            "486": "PANCHKULA",
            "485": "PANIPAT",
            "481": "REWARI",
            "482": "ROHTAK",
            "483": "SIRSA",
            "484": "SONEPAT",
            "487": "YAMUNA NAGAR"
        },
        constants.Jharkhand: {
            "516": "BOKARO",
            "517": "CHATRA",
            "518": "DEOGHAR",
            "519": "DHANBAD",
            "520": "DUMKA",
            "522": "GARHWA",
            "523": "GIRIDIH",
            "524": "GODDA",
            "525": "GUMLA",
            "527": "HAZARIBAGH",
            "521": "JAMTARA",
            "616": "KHARSAWAN",
            "650": "KHUNTI",
            "528": "KODERMA",
            "532": "LATEHAR",
            "529": "LOHARDAGA",
            "530": "PAKUR",
            "531": "PALAMAU",
            "651": "RAMGARH",
            "533": "RANCHI",
            "534": "SAHEBGANJ",
            "537": "SERAIKALA",
            "526": "SIMDEGA",
            "535": "SINGHBHUM EAST",
            "536": "SINGHBHUM WEST"
        },
        constants.Jammu_and_Kashmir: {
            "116": "ANANTNAG",
            "117": "BADGAM",
            "663": "BANDIPORA",
            "118": "BARAMULA",
            "124": "DODA",
            "665": "GANDERBAL",
            "119": "JAMMU",
            "120": "KARGIL",
            "121": "KATHUA",
            "659": "KISHTWAR",
            "664": "KULGAM",
            "122": "KUPWARA",
            "123": "LADAKH",
            "125": "POONCH",
            "126": "PULWAMA",
            "129": "RAJAURI",
            "662": "RAMBAN",
            "661": "REASI",
            "660": "SAMBA",
            "658": "SHOPIAN",
            "127": "SRINAGAR",
            "128": "UDHAMPUR"
        },
        constants.KARNATAKA: {
            "295": "BAGALKOT",
            "269": "BANGALORE-RUR",
            "270": "BANGALORE-URB",
            "271": "BELGAUM",
            "272": "BELLARY",
            "273": "BIDAR",
            "274": "BIJAPUR",
            "275": "CHAMARAJNAGAR",
            "647": "CHIKKABALLAPURA",
            "276": "CHIKMGALUR",
            "277": "CHITRADURGA",
            "278": "COORG",
            "279": "DAVANAGERE",
            "280": "DHARWAR",
            "281": "GADAG",
            "282": "GULBERGA",
            "283": "HASSAN",
            "284": "HAVERI",
            "285": "KOLAR",
            "286": "KOPPAL",
            "287": "MANDYA",
            "288": "MYSORE",
            "289": "NORTH KANARA",
            "290": "RAICHUR",
            "646": "RAMNAGARA",
            "291": "SHIMOGA",
            "292": "SOUTH KANARA",
            "293": "TUMKUR",
            "294": "UDIPI",
            "666": "YADGIR"
        },
        constants.Kerala: {
            "130": "ALLEPY",
            "131": "CANNANORE",
            "132": "ERNAKULUM",
            "133": "IDDIKI",
            "135": "KASARGOD",
            "134": "KOTTAYAM",
            "136": "KOZHIKODE",
            "137": "MALLAPURAM",
            "138": "PALGHAT",
            "143": "PATHNAMTHITA-N",
            "144": "PATHNAMTHITA-S",
            "139": "QUILON",
            "140": "TRICHUR",
            "141": "TRIVANDRUM",
            "142": "WYNAAD"
        },
        constants.Lakshadweep: {
            "598": "LAKSHADWEEP"
        },
        constants.Maharashtra: {
            "235": "AHMEDNAGAR",
            "236": "AKOLA",
            "237": "AMRAVATI",
            "238": "AURANGABAD",
            "240": "BEED",
            "239": "BHANDARA",
            "241": "BHULDANA",
            "242": "CHANDRAPUR",
            "245": "DHULE",
            "243": "GADCHIROLI",
            "267": "GONDIA",
            "268": "HINGOLI",
            "247": "JALGAON",
            "248": "JALNA",
            "250": "KOLHAPUR",
            "255": "LATUR",
            "246": "MUMBAI",
            "648": "MUMBAI SUBURBAN",
            "251": "NAGPUR",
            "252": "NANDED",
            "244": "NANDURBAR",
            "253": "NASIK",
            "254": "OSMANABAD",
            "256": "PARBHANI",
            "257": "PUNE (POONA)",
            "249": "RAIGAD",
            "258": "RATNAGIRI",
            "259": "SANGLI",
            "260": "SATARA",
            "262": "SHOLAPUR",
            "261": "SINDHUDURG",
            "263": "THANE",
            "264": "WARDHA",
            "266": "WASHIM",
            "265": "YEOTMAL",
            "703": "PALGHAR"
        },
        constants.Meghalaya: {
            "558": "GAROHILLS EAST",
            "563": "GAROHILLS SOUTH",
            "562": "GAROHILLS WEST",
            "559": "JAINTIA HILLS",
            "560": "KHASIHILLS EAST",
            "561": "KHASIHILLS WEST",
            "564": "RI-BHOI"
        },
        constants.Manipur: {
            "550": "BISHENPUR",
            "555": "CHANDEL",
            "553": "CHURACHANDPUR",
            "556": "IMPHAL EAST",
            "624": "IMPHAL WEST",
            "552": "SENAPATI",
            "554": "TAMENGLONG",
            "557": "THOUBAL",
            "551": "UKHRUL"
        },
        constants.Madhya_Pradesh: {
            "704": "AGAR-MALWA",
            "656": "ALIRAJPUR",
            "634": "ANUPPUR",
            "632": "ASHOKNAGAR",
            "145": "BALAGHAT",
            "189": "BARWANI",
            "146": "BETUL",
            "147": "BHIND",
            "148": "BHOPAL",
            "633": "BHURANPUR",
            "149": "CHHATTARPUR",
            "150": "CHHINDWARA",
            "151": "DAMOH",
            "152": "DATIA",
            "153": "DEWAS",
            "154": "DHAR",
            "186": "DINDORI",
            "155": "GUNA",
            "156": "GWALIOR",
            "184": "HARDA",
            "157": "HOSHANGABAD",
            "158": "INDORE",
            "159": "JABALPUR",
            "160": "JHABUA",
            "185": "KATNI",
            "165": "KHANDWA",
            "166": "KHARGONE",
            "162": "MANDASAUR",
            "161": "MANDLA",
            "163": "MORENA",
            "164": "NARSIMHAPUR",
            "187": "NEEMUCH",
            "167": "PANNA",
            "169": "RAISEN",
            "168": "RAJGARH",
            "170": "RATLAM",
            "171": "REWA",
            "172": "SAGAR",
            "173": "SATNA",
            "174": "SEHORE",
            "175": "SEONI",
            "176": "SHAHDOL",
            "177": "SHAJAPUR",
            "188": "SHEOPUR",
            "178": "SHIVPURI",
            "179": "SIDHI",
            "654": "SINGRAULI",
            "181": "TIKAMGARH",
            "182": "UJJAIN",
            "190": "UMARIA",
            "183": "VIDISHA"
        },
        constants.Mizoram: {
            "599": "AIJAL",
            "620": "CHAMPHAI",
            "601": "CHHIMTUIPUI",
            "619": "KOLASIB",
            "622": "LAWNGTLAI",
            "600": "LUMGLEI",
            "609": "MAMIT",
            "623": "SAIHA",
            "621": "SERCHIP"
        },
        constants.Nagaland: {
            "638": "DIMAPUR",
            "637": "KIPHERE",
            "565": "KOHIMA",
            "636": "LONGLENG",
            "566": "MOKOCHANG",
            "570": "MON",
            "639": "PEREN",
            "568": "PHEK",
            "567": "TUENSENG",
            "571": "WOKHA",
            "569": "ZUNHEBOTO"
        },
        constants.ODISHA: {
            "296": "ANGUL",
            "297": "BALASORE",
            "316": "BARAGARH",
            "298": "BHADRAK",
            "299": "BOLANGIR",
            "300": "BOUDH",
            "301": "CUTTACK",
            "317": "DEOGARH",
            "302": "DHENKANAL",
            "318": "GAJAPATI",
            "303": "GANJAM",
            "309": "JAGATSINGHPUR",
            "304": "JAJPUR",
            "319": "JHARSUGUDA",
            "305": "KALAHANDI",
            "312": "KANDHAMAL",
            "307": "KENDRAPADA",
            "306": "KEONJHAR",
            "320": "KHURDA",
            "308": "KORAPUT",
            "311": "MALKANGIRI",
            "310": "MAYURBHANJ",
            "322": "NABARANGPUR",
            "324": "NARAYANGARH",
            "321": "NAYAGARH",
            "323": "NUAPARA",
            "313": "PURI",
            "325": "RAYAGADA",
            "314": "SAMBALPUR",
            "326": "SONEPUR",
            "315": "SUNDERGARH"
        },
        constants.Punjab: {
            "327": "AMRITSAR",
            "649": "BARNALA",
            "328": "BHATINDA",
            "329": "FARIDKOTE",
            "331": "FATEHGARH",
            "689": "FAZILKA",
            "330": "FEROZPUR",
            "332": "GURDASPUR",
            "333": "HOSHIARPUR",
            "334": "JULLANDER",
            "335": "KAPURTHALA",
            "336": "LUDHIANA",
            "337": "MAANSA",
            "608": "MOGA",
            "341": "MUKTSAR",
            "678": "PATHANKOT",
            "338": "PATIALA",
            "339": "ROOPNAGAR",
            "340": "SANGRUR",
            "612": "SAS NAGAR",
            "610": "TARAN TARAN",
            "342": "SHAHID BHAGAT SINGH NAGAR"
        },
        constants.Pondicherry: {
            "602": "KARAIKAL",
            "603": "MAHE",
            "604": "PONDICHERRY",
            "605": "YANAM"
        },
        constants.Rajasthan: {
            "343": "AJMER",
            "344": "ALWAR",
            "345": "BANSAWARA",
            "346": "BARAN",
            "347": "BARMER",
            "348": "BHARATPUR",
            "349": "BHILWARA",
            "350": "BIKANER",
            "351": "BUNDI",
            "352": "CHITORGARH",
            "353": "CHURU",
            "356": "DAUSA",
            "354": "DHOLPUR",
            "355": "DUNGARPUR",
            "357": "GANGANAGAR",
            "358": "HANUMANGARH",
            "359": "JAIPUR",
            "360": "JAISALMER",
            "361": "JALORE",
            "362": "JHALAWAR",
            "363": "JHUNJHUNU",
            "364": "JODHPUR",
            "606": "KARAULI",
            "365": "KOTA",
            "366": "NAGAUR",
            "367": "PALI",
            "653": "PRATAPGARH",
            "368": "RAJ SAMAND",
            "369": "SAWAIMADHOPUR",
            "370": "SIKAR",
            "371": "SIROHI",
            "372": "TONK",
            "373": "UDAIPUR"
        },
        constants.Sikkim: {
            "572": "SIKKIM EAST",
            "573": "SIKKIM NORTH",
            "574": "SIKKIM SOUTH",
            "575": "SIKKIM WEST"
        },
        constants.Telangana: {
            "001": "ADILABAD",
            "008": "HYDERABAD",
            "009": "KARIMNAGAR",
            "010": "KHAMMAM",
            "015": "MEDAK",
            "014": "MEHBUBNAGAR",
            "016": "NALGONDA",
            "018": "NIZAMABAD",
            "013": "RANGA REDDY",
            "022": "WARANGAL"
        },
        constants.Tamil_Nadu: {
            "194": "ANNA",
            "192": "ARIYALUR",
            "191": "CHINGELPET",
            "193": "COIMBATORE",
            "220": "CUDDALORE",
            "208": "DHARMAPURI",
            "228": "DINDIGUL",
            "233": "ERODE",
            "196": "KAMARAJAR",
            "222": "KANCHIPURAM",
            "195": "KANYA-KUMARI",
            "230": "KARUR",
            "628": "KRISHNAGIRI",
            "197": "MADRAS",
            "198": "MADURAI",
            "232": "NAGAPATTINAM",
            "234": "NAMAKKAL",
            "217": "NEGEL Q MILLIETH",
            "214": "NEL KATTABOMMAN",
            "200": "NILGIRIS",
            "199": "NORTH ARCOT",
            "205": "P MUTHURAMALING",
            "223": "PERAMBALUR",
            "203": "PERIYAR",
            "204": "PUDUKOTTAI",
            "211": "QUAI-DE-MILLET",
            "206": "RAMANATHAPURAM",
            "207": "SALEM",
            "229": "SIVAGANGA",
            "209": "SOUTH ARCOT",
            "210": "THANJAVUR",
            "227": "THENI",
            "224": "THOOTHUKUDI",
            "201": "TIRU SAMBUVARYR",
            "225": "TIRUNELVELI",
            "655": "TIRUPPUR",
            "218": "TIRUVALLUR",
            "219": "TIRUVANNAMALAI",
            "231": "TIRUVARUR",
            "213": "TRICHY-EAST",
            "212": "TRICHY-WEST",
            "215": "V CHIDAMBARANAR",
            "202": "VELLORE AMBEDKR",
            "216": "VILLU RAMA PADAYACHI",
            "221": "VILLUPURAM",
            "226": "VIRUDHUNAGAR"
        },
        constants.Tripura: {
            "576": "DHALAI",
            "577": "TRIPURA NORTH",
            "578": "TRIPURA SOUTH",
            "579": "TRIPURA WEST"
        },
        constants.Uttar_Pradesh: {
            "374": "AGRA",
            "376": "ALIGARH",
            "378": "ALLAHABAD",
            "377": "ALLAHABADLOCAL",
            "375": "AMBEDKAR NAGAR",
            "679": "AMETHI",
            "414": "AMROHA",
            "613": "AURAIYA",
            "379": "AZAMGARH",
            "391": "BAGHPAT",
            "380": "BAHRAICH",
            "381": "BALLIA",
            "382": "BALRAMPUR",
            "383": "BANDA",
            "385": "BARA BANKI",
            "387": "BAREILLY",
            "388": "BASTI",
            "389": "BHADOI",
            "390": "BIJNOR",
            "392": "BUDAUN",
            "393": "BULANDSHAHR",
            "615": "CHANDAULI",
            "635": "CHITRUKUT",
            "394": "DEORIA",
            "395": "ETAH",
            "396": "ETAWAH",
            "397": "FAIZABAD",
            "399": "FARRUKHABAD",
            "401": "FATEHPUR",
            "400": "FEROZABAD",
            "406": "GAUTAM BUDH NAGAR",
            "405": "GAZIPUR",
            "430": "GHAZIABAD",
            "407": "GONDA",
            "409": "GORAKHPUR",
            "410": "HAMIRPUR",
            "692": "HAPUR",
            "412": "HARDOI",
            "411": "HATHRAS",
            "413": "JALAUN",
            "415": "JAUNPUR",
            "417": "JHANSI",
            "614": "KANNAUJ",
            "420": "KANPUR CITY",
            "419": "KANPUR DEHAT",
            "677": "KANSGANJ",
            "418": "KAUSHAMBI",
            "416": "KAUSHINAGAR",
            "421": "KHERI",
            "422": "LALITPUR",
            "423": "LUCKNOW",
            "424": "MAHARAJGANJ",
            "426": "MAHOBA",
            "425": "MAINPURI",
            "427": "MATHURA",
            "428": "MAU",
            "429": "MEERUT",
            "431": "MIRZAPUR",
            "432": "MORADABAD",
            "433": "MUZAFFARNAGAR",
            "446": "PADROUNA",
            "434": "PILBHIT",
            "435": "PRATAPGARH",
            "436": "RAE-BAREILLY",
            "437": "RAMPUR",
            "438": "SAHARANPUR",
            "690": "SAMBHAL",
            "398": "SANT KABIR NAGAR",
            "404": "SANT RAVI NAGAR",
            "447": "SHAHJAHANPUR",
            "691": "SHAMLI",
            "408": "SHRAVASTI",
            "439": "SIDHARATH NAGAR",
            "440": "SITAPUR",
            "448": "SONBHADRA",
            "441": "SULTANPUR",
            "443": "UNNAO",
            "444": "VARANASI",
            "445": "VARANASI-LOCAL"
        },
        constants.Uttarakhand: {
            "538": "ALMORA",
            "539": "BAGESHWAR",
            "540": "CHAMOLI",
            "541": "CHAMPAWAT",
            "542": "DEHRADUN",
            "543": "HARIDWAR",
            "544": "NAINITAL",
            "545": "PAURI GARHWAL",
            "546": "PITHORAGARH",
            "547": "RUDRAPRAYAG",
            "442": "TEHRI-GARHWAL",
            "548": "UDHAM SINGH NGR",
            "549": "UTTARKASHI"
        },
        constants.West_Bengal: {
            "466": "24-PARGANAS-N",
            "467": "24-PARGANAS-S",
            "449": "BANKURA",
            "450": "BIRBHUM",
            "451": "BURDWAN",
            "453": "CALCUTTA",
            "452": "CALCUTTA-LOCAL",
            "454": "COOCH-BEHAR",
            "470": "DAKSHIN DINAJPR",
            "456": "DARJEELING",
            "455": "DARJEELING(HS)",
            "457": "HOOGHLY",
            "458": "HOWRAH",
            "459": "JALPAIGURI",
            "460": "JALPAIGURIWEST (DO NOT USE)",
            "461": "MALDA",
            "463": "MURSHIDABAD",
            "464": "NADIA",
            "652": "PASCHIM MEDINIPUR",
            "462": "PURBA MEDINIPUR",
            "465": "PURULIA",
            "469": "UTTAR DINAJPUR",
            "468": "WEST DINAJPUR",
            "702": "ALIPURDUAR"
        }
    }

    @staticmethod
    def fetch_attributes(marker):
        dto = {}
        for attr in marker.attrs:
            if attr != "div_data":
                dto[attr] = marker.attrs[attr]
        return dto

    def fetch_details(self):
        curl_base_command = self.curl_template_map[constants.HPCL_CURL]
        for state in self.District_Codes:
            for code in self.District_Codes[state]:
                curl_command = curl_base_command.replace('__city_code__', code)
                try:
                    res = utils.robust_curl(curl_command, sleep_seconds=0)
                    parsed_res = BeautifulSoup(res, "lxml")
                    markers = parsed_res.markers.findAll('marker')
                    for marker in markers:
                        get_dto = self.fetch_attributes(marker)
                        self.store_dto(dto=get_dto)
                except:
                    logging.warning("Error while fetching data for curl : " + curl_command)
